spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:mysql://auth-db:3306/db_auth
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=airflytrip-dev-secret-key-change-this-in-production-airflytrip-dev-secret-key
app.jwt.expiration-ms=86400000
