spring.datasource.url=jdbc:mysql://payment-db:3306/db_payments
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
services.trip.url=${SERVICES_TRIP_URL:http://trip-service:8086}
services.reservation.url=${SERVICES_RESERVATION_URL:http://reservation-service:8087}
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
