spring.datasource.url=jdbc:mysql://vehicle-db:3306/db_vehicles
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
services.terminal.url=${SERVICES_TERMINAL_URL:http://terminal-service:8083}
services.charging-station.url=${SERVICES_CHARGING_STATION_URL:http://charging-station-service:8091}
