spring.datasource.url=jdbc:mysql://tariff-db:3306/db_tariffs
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
services.route.url=${SERVICES_ROUTE_URL:http://route-service:8085}
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
